name: Create a new release
on:
  push:
    branches:
      - main
jobs:
  create_release:
    name: Bump tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: '0'
          persist-credentials: false
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          token: ${{ secrets.ACTIONS_TOKEN }}
